#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorBeamsPanelLayout, "rig_editor_beams_panel.layout");
class RigEditorBeamsPanelLayout : public wraps::BaseLayout
{

public:

	RigEditorBeamsPanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorBeamsPanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_beams_panel, "beams_panel");
	MyGUI::Window* m_beams_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_flags_label, "flags_label");
	MyGUI::TextBox* m_flags_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_flag_i_checkbox, "flag_i_checkbox");
	MyGUI::Button* m_flag_i_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_flag_r_checkbox, "flag_r_checkbox");
	MyGUI::Button* m_flag_r_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_flag_s_checkbox, "flag_s_checkbox");
	MyGUI::Button* m_flag_s_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_flags_tooltip_label, "flags_tooltip_label");
	MyGUI::TextBox* m_flags_tooltip_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_beam_type_combobox, "beam_type_combobox");
	MyGUI::ComboBox* m_beam_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_beam_type_label, "beam_type_label");
	MyGUI::TextBox* m_beam_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_detacher_group_label, "detacher_group_label");
	MyGUI::TextBox* m_detacher_group_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_detacher_group_editbox, "detacher_group_editbox");
	MyGUI::EditBox* m_detacher_group_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_ext_breaklimit_label, "ext_breaklimit_label");
	MyGUI::TextBox* m_ext_breaklimit_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorBeamsPanelLayout, m_ext_breaklimit_editbox, "ext_breaklimit_editbox");
	MyGUI::EditBox* m_ext_breaklimit_editbox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

