#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(TerrainSelectorLayout, "TerrainSelector.layout");
class TerrainSelectorLayout : public wraps::BaseLayout
{

public:

	TerrainSelectorLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~TerrainSelectorLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_next, "next");
	MyGUI::Button* m_next;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_back, "back");
	MyGUI::Button* m_back;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_select, "select");
	MyGUI::Button* m_select;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_track_name, "track_name");
	MyGUI::EditBox* m_track_name;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_desc, "desc");
	MyGUI::TextBox* m_desc;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_p1, "p1");
	MyGUI::ImageBox* m_p1;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m__TerrainList, "_TerrainList");
	MyGUI::Window* m__TerrainList;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_terrainlistbox, "terrainlistbox");
	MyGUI::ListBox* m_terrainlistbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(TerrainSelectorLayout, m_searchbox, "searchbox");
	MyGUI::EditBox* m_searchbox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

