// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_DebugOptionsLayout.h"

using namespace RoR;
using namespace GUI;

DebugOptionsLayout::DebugOptionsLayout(MyGUI::Widget *_parent)
{
    initialiseByAttributes(this, _parent);
}

DebugOptionsLayout::~DebugOptionsLayout()
{
}
