#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(GameChatBoxLayout, "Chatbox.layout");
class GameChatBoxLayout : public wraps::BaseLayout
{

public:

	GameChatBoxLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~GameChatBoxLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(GameChatBoxLayout, m_Console_MainBox, "Console_MainBox");
	MyGUI::EditBox* m_Console_MainBox;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameChatBoxLayout, m_Console_TextBox, "Console_TextBox");
	MyGUI::EditBox* m_Console_TextBox;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameChatBoxLayout, m_Console_Send, "Console_Send");
	MyGUI::Button* m_Console_Send;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

