
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_RigEditorHelpWindowLayout.h"

using namespace RoR;
using namespace GUI;

RigEditorHelpWindowLayout::RigEditorHelpWindowLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

RigEditorHelpWindowLayout::~RigEditorHelpWindowLayout()
{
}

