#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorHelpWindowLayout, "rig_editor_help_window.layout");
class RigEditorHelpWindowLayout : public wraps::BaseLayout
{

public:

	RigEditorHelpWindowLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorHelpWindowLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHelpWindowLayout, m_rig_editor_help_window, "rig_editor_help_window");
	MyGUI::Window* m_rig_editor_help_window;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHelpWindowLayout, m_help_view, "help_view");
	MyGUI::EditBox* m_help_view;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

