#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorHydrosPanelLayout, "rig_editor_hydros_panel.layout");
class RigEditorHydrosPanelLayout : public wraps::BaseLayout
{

public:

	RigEditorHydrosPanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorHydrosPanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_beams_panel, "beams_panel");
	MyGUI::Window* m_beams_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flags_label, "flags_label");
	MyGUI::TextBox* m_flags_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_i_checkbox, "flag_i_checkbox");
	MyGUI::Button* m_flag_i_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_a_checkbox, "flag_a_checkbox");
	MyGUI::Button* m_flag_a_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_s_checkbox, "flag_s_checkbox");
	MyGUI::Button* m_flag_s_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flags_tooltip_label, "flags_tooltip_label");
	MyGUI::TextBox* m_flags_tooltip_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_beam_type_combobox, "beam_type_combobox");
	MyGUI::ComboBox* m_beam_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_beam_type_label, "beam_type_label");
	MyGUI::TextBox* m_beam_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_detacher_group_label, "detacher_group_label");
	MyGUI::TextBox* m_detacher_group_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_detacher_group_editbox, "detacher_group_editbox");
	MyGUI::EditBox* m_detacher_group_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_extension_factor_label, "extension_factor_label");
	MyGUI::TextBox* m_extension_factor_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_extension_factor_editbox, "extension_factor_editbox");
	MyGUI::EditBox* m_extension_factor_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_r_checkbox, "flag_r_checkbox");
	MyGUI::Button* m_flag_r_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_v_checkbox, "flag_v_checkbox");
	MyGUI::Button* m_flag_v_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_x_checkbox, "flag_x_checkbox");
	MyGUI::Button* m_flag_x_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_u_checkbox, "flag_u_checkbox");
	MyGUI::Button* m_flag_u_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_e_checkbox, "flag_e_checkbox");
	MyGUI::Button* m_flag_e_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_y_checkbox, "flag_y_checkbox");
	MyGUI::Button* m_flag_y_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_h_checkbox, "flag_h_checkbox");
	MyGUI::Button* m_flag_h_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_flag_g_checkbox, "flag_g_checkbox");
	MyGUI::Button* m_flag_g_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_start_delay_label, "start_delay_label");
	MyGUI::TextBox* m_start_delay_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_start_delay_editbox, "start_delay_editbox");
	MyGUI::EditBox* m_start_delay_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_stop_delay_editbox, "stop_delay_editbox");
	MyGUI::EditBox* m_stop_delay_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_start_function_editbox, "start_function_editbox");
	MyGUI::EditBox* m_start_function_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_stop_function_editbox, "stop_function_editbox");
	MyGUI::EditBox* m_stop_function_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_stop_delay_label, "stop_delay_label");
	MyGUI::TextBox* m_stop_delay_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_start_function_label, "start_function_label");
	MyGUI::TextBox* m_start_function_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorHydrosPanelLayout, m_stop_function_label, "stop_function_label");
	MyGUI::TextBox* m_stop_function_label;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

