
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
//
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
// ----------------------------------------------------------------------------

#include "GUI_RigEditorRigPropertiesWindowLayout.h"

using namespace RoR;
using namespace GUI;

RigEditorRigPropertiesWindowLayout::RigEditorRigPropertiesWindowLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

RigEditorRigPropertiesWindowLayout::~RigEditorRigPropertiesWindowLayout()
{
}

