
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
//
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
// ----------------------------------------------------------------------------

#include "GUI_RigEditorFilePropertiesWindowLayout.h"

using namespace RoR;
using namespace GUI;

RigEditorFilePropertiesWindowLayout::RigEditorFilePropertiesWindowLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

RigEditorFilePropertiesWindowLayout::~RigEditorFilePropertiesWindowLayout()
{
}

