
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_RigEditorLandVehiclePropertiesWindowLayout.h"

using namespace RoR;
using namespace GUI;

RigEditorLandVehiclePropertiesWindowLayout::RigEditorLandVehiclePropertiesWindowLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

RigEditorLandVehiclePropertiesWindowLayout::~RigEditorLandVehiclePropertiesWindowLayout()
{
}

