#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR {
namespace GUI {

ATTRIBUTE_CLASS_LAYOUT(GameChatBoxLayout, "Chatbox.layout");
class GameChatBoxLayout : public wraps::BaseLayout
{

public:

    GameChatBoxLayout(MyGUI::Widget* _parent = nullptr);
    virtual ~GameChatBoxLayout();

protected:

    //%LE Widget_Declaration list start
    ATTRIBUTE_FIELD_WIDGET_NAME(GameChatBoxLayout, m_Chatbox_MainBox, "Chatbox_MainBox");
    MyGUI::EditBox* m_Chatbox_MainBox;

    ATTRIBUTE_FIELD_WIDGET_NAME(GameChatBoxLayout, m_Chatbox_TextBox, "Chatbox_TextBox");
    MyGUI::EditBox* m_Chatbox_TextBox;

    //%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

