#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(GameSettingsLayout, "settings.layout");
class GameSettingsLayout : public wraps::BaseLayout
{

public:

	GameSettingsLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~GameSettingsLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_tabCtrl, "tabCtrl");
	MyGUI::TabControl* m_tabCtrl;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_lang, "lang");
	MyGUI::ComboBox* m_lang;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_gearbox_mode, "gearbox_mode");
	MyGUI::ComboBox* m_gearbox_mode;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_arc_mode, "arc_mode");
	MyGUI::Button* m_arc_mode;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_d_cam_pitch, "d_cam_pitch");
	MyGUI::Button* m_d_cam_pitch;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fovexternal, "fovexternal");
	MyGUI::EditBox* m_fovexternal;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fovinternal, "fovinternal");
	MyGUI::EditBox* m_fovinternal;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_clear_cache, "clear_cache");
	MyGUI::Button* m_clear_cache;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_regen_cache, "regen_cache");
	MyGUI::Button* m_regen_cache;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_enable_replay, "enable_replay");
	MyGUI::Button* m_enable_replay;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_speed_unit, "speed_unit");
	MyGUI::ComboBox* m_speed_unit;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_digital_speedo, "digital_speedo");
	MyGUI::Button* m_digital_speedo;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_hq_screenshots, "hq_screenshots");
	MyGUI::Button* m_hq_screenshots;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_render_sys, "render_sys");
	MyGUI::ComboBox* m_render_sys;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fsaa, "fsaa");
	MyGUI::ComboBox* m_fsaa;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fullscreen, "fullscreen");
	MyGUI::Button* m_fullscreen;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_vsync, "vsync");
	MyGUI::Button* m_vsync;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_resolution, "resolution");
	MyGUI::ComboBox* m_resolution;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_tex_filter, "tex_filter");
	MyGUI::ComboBox* m_tex_filter;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_sky_type, "sky_type");
	MyGUI::ComboBox* m_sky_type;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_shadow_type, "shadow_type");
	MyGUI::ComboBox* m_shadow_type;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_sightrange, "sightrange");
	MyGUI::ScrollBar* m_sightrange;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_sh_pf_opti, "sh_pf_opti");
	MyGUI::Button* m_sh_pf_opti;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_water_type, "water_type");
	MyGUI::ComboBox* m_water_type;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_e_waves, "e_waves");
	MyGUI::Button* m_e_waves;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_vegetation, "vegetation");
	MyGUI::ComboBox* m_vegetation;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_sightrange_indicator, "sightrange_indicator");
	MyGUI::EditBox* m_sightrange_indicator;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_psystem, "psystem");
	MyGUI::Button* m_psystem;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_mirrors, "mirrors");
	MyGUI::Button* m_mirrors;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_mblur, "mblur");
	MyGUI::Button* m_mblur;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_hq_ref, "hq_ref");
	MyGUI::Button* m_hq_ref;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_heathaze, "heathaze");
	MyGUI::Button* m_heathaze;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_hdr, "hdr");
	MyGUI::Button* m_hdr;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_dof, "dof");
	MyGUI::Button* m_dof;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_skidmarks, "skidmarks");
	MyGUI::Button* m_skidmarks;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_glow, "glow");
	MyGUI::Button* m_glow;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_sunburn, "sunburn");
	MyGUI::Button* m_sunburn;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_light_source_effects, "light_source_effects");
	MyGUI::ComboBox* m_light_source_effects;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_autohide_chatbox, "autohide_chatbox");
	MyGUI::Button* m_autohide_chatbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fps_limiter_slider, "fps_limiter_slider");
	MyGUI::ScrollBar* m_fps_limiter_slider;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_fps_limiter_indicator, "fps_limiter_indicator");
	MyGUI::EditBox* m_fps_limiter_indicator;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_disable_multithreading, "disable_multithreading");
	MyGUI::Button* m_disable_multithreading;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_disable_inter_collsion, "disable_inter_collsion");
	MyGUI::Button* m_disable_inter_collsion;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_disable_intra_collision, "disable_intra_collision");
	MyGUI::Button* m_disable_intra_collision;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_enable_async_physics, "enable_async_physics");
	MyGUI::Button* m_enable_async_physics;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_d_creak_sound, "d_creak_sound");
	MyGUI::Button* m_d_creak_sound;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_audio_dev, "audio_dev");
	MyGUI::ComboBox* m_audio_dev;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_volume_slider, "volume_slider");
	MyGUI::ScrollBar* m_volume_slider;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_volume_indicator, "volume_indicator");
	MyGUI::EditBox* m_volume_indicator;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_keymapping, "keymapping");
	MyGUI::MultiListBox* m_keymapping;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_key_name, "key_name");
	MyGUI::MultiListItem* m_key_name;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_key_button, "key_button");
	MyGUI::MultiListItem* m_key_button;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_keymap_group, "keymap_group");
	MyGUI::ComboBox* m_keymap_group;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_change_key, "change_key");
	MyGUI::Button* m_change_key;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_savebtn, "savebtn");
	MyGUI::Button* m_savebtn;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_key_mapping_window, "key_mapping_window");
	MyGUI::Window* m_key_mapping_window;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_key_mapping_window_text, "key_mapping_window_text");
	MyGUI::EditBox* m_key_mapping_window_text;

	ATTRIBUTE_FIELD_WIDGET_NAME(GameSettingsLayout, m_key_mapping_window_info, "key_mapping_window_info");
	MyGUI::EditBox* m_key_mapping_window_info;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

