#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorCommands2PanelLayout, "rig_editor_commands2_panel.layout");
class RigEditorCommands2PanelLayout : public wraps::BaseLayout
{

public:

	RigEditorCommands2PanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorCommands2PanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_commands2_panel, "commands2_panel");
	MyGUI::Window* m_commands2_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_beam_type_combobox, "beam_type_combobox");
	MyGUI::ComboBox* m_beam_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_beam_type_label, "beam_type_label");
	MyGUI::TextBox* m_beam_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_detacher_group_label, "detacher_group_label");
	MyGUI::TextBox* m_detacher_group_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_detacher_group_editbox, "detacher_group_editbox");
	MyGUI::EditBox* m_detacher_group_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contraction_rate_label, "contraction_rate_label");
	MyGUI::TextBox* m_contraction_rate_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contraction_rate_editbox, "contraction_rate_editbox");
	MyGUI::EditBox* m_contraction_rate_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extension_rate_label, "extension_rate_label");
	MyGUI::TextBox* m_extension_rate_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extension_rate_editbox, "extension_rate_editbox");
	MyGUI::EditBox* m_extension_rate_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_i_checkbox, "flag_i_checkbox");
	MyGUI::Button* m_flag_i_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_r_checkbox, "flag_r_checkbox");
	MyGUI::Button* m_flag_r_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_c_checkbox, "flag_c_checkbox");
	MyGUI::Button* m_flag_c_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flags_tooltip_label, "flags_tooltip_label");
	MyGUI::TextBox* m_flags_tooltip_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contraction_limit_label, "contraction_limit_label");
	MyGUI::TextBox* m_contraction_limit_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contraction_limit_editbox, "contraction_limit_editbox");
	MyGUI::EditBox* m_contraction_limit_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extension_limit_label, "extension_limit_label");
	MyGUI::TextBox* m_extension_limit_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extension_limit_editbox, "extension_limit_editbox");
	MyGUI::EditBox* m_extension_limit_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contract_key_label, "contract_key_label");
	MyGUI::TextBox* m_contract_key_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extend_key_label, "extend_key_label");
	MyGUI::TextBox* m_extend_key_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_contract_key_combobox, "contract_key_combobox");
	MyGUI::ComboBox* m_contract_key_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_extend_key_combobox, "extend_key_combobox");
	MyGUI::ComboBox* m_extend_key_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_f_checkbox, "flag_f_checkbox");
	MyGUI::Button* m_flag_f_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_p_checkbox, "flag_p_checkbox");
	MyGUI::Button* m_flag_p_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_flag_o_checkbox, "flag_o_checkbox");
	MyGUI::Button* m_flag_o_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_description_editbox, "description_editbox");
	MyGUI::EditBox* m_description_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_start_delay_label, "start_delay_label");
	MyGUI::TextBox* m_start_delay_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_start_delay_editbox, "start_delay_editbox");
	MyGUI::EditBox* m_start_delay_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_stop_delay_editbox, "stop_delay_editbox");
	MyGUI::EditBox* m_stop_delay_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_start_function_editbox, "start_function_editbox");
	MyGUI::EditBox* m_start_function_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_stop_function_editbox, "stop_function_editbox");
	MyGUI::EditBox* m_stop_function_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_stop_delay_label, "stop_delay_label");
	MyGUI::TextBox* m_stop_delay_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_start_function_label, "start_function_label");
	MyGUI::TextBox* m_start_function_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_stop_function_label, "stop_function_label");
	MyGUI::TextBox* m_stop_function_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_affect_engine_label, "affect_engine_label");
	MyGUI::TextBox* m_affect_engine_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_affect_engine_editbox, "affect_engine_editbox");
	MyGUI::EditBox* m_affect_engine_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorCommands2PanelLayout, m_needs_engine_checkbox, "needs_engine_checkbox");
	MyGUI::Button* m_needs_engine_checkbox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

