#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorMeshWheels2PanelLayout, "rig_editor_meshwheels2_panel.layout");
class RigEditorMeshWheels2PanelLayout : public wraps::BaseLayout
{

public:

	RigEditorMeshWheels2PanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorMeshWheels2PanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_meshwheels2_panel, "meshwheels2_panel");
	MyGUI::Window* m_meshwheels2_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_wheel_type_combobox, "wheel_type_combobox");
	MyGUI::ComboBox* m_wheel_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_wheel_type_label, "wheel_type_label");
	MyGUI::TextBox* m_wheel_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_material_name_label, "tyre_material_name_label");
	MyGUI::TextBox* m_tyre_material_name_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_node_axis_a_editbox, "node_axis_a_editbox");
	MyGUI::EditBox* m_node_axis_a_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_radius_label, "rim_radius_label");
	MyGUI::TextBox* m_rim_radius_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_radius_editbox, "rim_radius_editbox");
	MyGUI::EditBox* m_rim_radius_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_spring_label, "tyre_spring_label");
	MyGUI::TextBox* m_tyre_spring_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_spring_editbox, "tyre_spring_editbox");
	MyGUI::EditBox* m_tyre_spring_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_mass_label, "mass_label");
	MyGUI::TextBox* m_mass_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_mass_editbox, "mass_editbox");
	MyGUI::EditBox* m_mass_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_propulsion_label, "propulsion_label");
	MyGUI::TextBox* m_propulsion_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_mesh_name_editbox, "rim_mesh_name_editbox");
	MyGUI::EditBox* m_rim_mesh_name_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_mesh_name_label, "rim_mesh_name_label");
	MyGUI::TextBox* m_rim_mesh_name_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_material_name_editbox, "tyre_material_name_editbox");
	MyGUI::EditBox* m_tyre_material_name_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_spring_label, "rim_spring_label");
	MyGUI::TextBox* m_rim_spring_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_spring_editbox, "rim_spring_editbox");
	MyGUI::EditBox* m_rim_spring_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_damping_label, "rim_damping_label");
	MyGUI::TextBox* m_rim_damping_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_damping_editbox, "rim_damping_editbox");
	MyGUI::EditBox* m_rim_damping_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_num_rays_label, "num_rays_label");
	MyGUI::TextBox* m_num_rays_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_num_rays_editbox, "num_rays_editbox");
	MyGUI::EditBox* m_num_rays_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_damping_label, "tyre_damping_label");
	MyGUI::TextBox* m_tyre_damping_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_break_threshold_label, "rim_break_threshold_label");
	MyGUI::TextBox* m_rim_break_threshold_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_deform_threshold_label, "rim_deform_threshold_label");
	MyGUI::TextBox* m_rim_deform_threshold_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_damping_editbox, "tyre_damping_editbox");
	MyGUI::EditBox* m_tyre_damping_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_break_threshold_editbox, "rim_break_threshold_editbox");
	MyGUI::EditBox* m_rim_break_threshold_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rim_deform_threshold_editbox, "rim_deform_threshold_editbox");
	MyGUI::EditBox* m_rim_deform_threshold_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_propulsion_combobox, "propulsion_combobox");
	MyGUI::ComboBox* m_propulsion_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_braking_label, "braking_label");
	MyGUI::TextBox* m_braking_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_braking_combobox, "braking_combobox");
	MyGUI::ComboBox* m_braking_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_side_label, "side_label");
	MyGUI::TextBox* m_side_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_nodes_section_label, "nodes_section_label");
	MyGUI::TextBox* m_nodes_section_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_node_axis_a_label, "node_axis_a_label");
	MyGUI::TextBox* m_node_axis_a_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_node_axis_b_label, "node_axis_b_label");
	MyGUI::TextBox* m_node_axis_b_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_node_axis_b_editbox, "node_axis_b_editbox");
	MyGUI::EditBox* m_node_axis_b_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rigidity_node_label, "rigidity_node_label");
	MyGUI::TextBox* m_rigidity_node_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_rigidity_node_editbox, "rigidity_node_editbox");
	MyGUI::EditBox* m_rigidity_node_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_arm_node_label, "arm_node_label");
	MyGUI::TextBox* m_arm_node_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_arm_node_editbox, "arm_node_editbox");
	MyGUI::EditBox* m_arm_node_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_radius_label, "tyre_radius_label");
	MyGUI::TextBox* m_tyre_radius_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_tyre_radius_editbox, "tyre_radius_editbox");
	MyGUI::EditBox* m_tyre_radius_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorMeshWheels2PanelLayout, m_side_combobox, "side_combobox");
	MyGUI::ComboBox* m_side_combobox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

