#pragma once

// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "ForwardDeclarations.h"
#include "BaseLayout.h"

namespace RoR
{

namespace GUI
{
	
ATTRIBUTE_CLASS_LAYOUT(RigEditorShocksPanelLayout, "rig_editor_shocks_panel.layout");
class RigEditorShocksPanelLayout : public wraps::BaseLayout
{

public:

	RigEditorShocksPanelLayout(MyGUI::Widget* _parent = nullptr);
	virtual ~RigEditorShocksPanelLayout();

protected:

	//%LE Widget_Declaration list start
	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_shocks_panel, "shocks_panel");
	MyGUI::Window* m_shocks_panel;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_beam_type_combobox, "beam_type_combobox");
	MyGUI::ComboBox* m_beam_type_combobox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_beam_type_label, "beam_type_label");
	MyGUI::TextBox* m_beam_type_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_detacher_group_label, "detacher_group_label");
	MyGUI::TextBox* m_detacher_group_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_detacher_group_editbox, "detacher_group_editbox");
	MyGUI::EditBox* m_detacher_group_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_spring_label, "spring_label");
	MyGUI::TextBox* m_spring_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_spring_editbox, "spring_editbox");
	MyGUI::EditBox* m_spring_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_flags_label, "flags_label");
	MyGUI::TextBox* m_flags_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_flag_i_checkbox, "flag_i_checkbox");
	MyGUI::Button* m_flag_i_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_flag_L_checkbox, "flag_L_checkbox");
	MyGUI::Button* m_flag_L_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_flag_R_checkbox, "flag_R_checkbox");
	MyGUI::Button* m_flag_R_checkbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_flags_tooltip_label, "flags_tooltip_label");
	MyGUI::TextBox* m_flags_tooltip_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_contraction_limit_label, "contraction_limit_label");
	MyGUI::TextBox* m_contraction_limit_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_contraction_limit_editbox, "contraction_limit_editbox");
	MyGUI::EditBox* m_contraction_limit_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_extension_limit_label, "extension_limit_label");
	MyGUI::TextBox* m_extension_limit_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_extension_limit_editbox, "extension_limit_editbox");
	MyGUI::EditBox* m_extension_limit_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_precompression_label, "precompression_label");
	MyGUI::TextBox* m_precompression_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_precompression_editbox, "precompression_editbox");
	MyGUI::EditBox* m_precompression_editbox;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_damping_label, "damping_label");
	MyGUI::TextBox* m_damping_label;

	ATTRIBUTE_FIELD_WIDGET_NAME(RigEditorShocksPanelLayout, m_damping_editbox, "damping_editbox");
	MyGUI::EditBox* m_damping_editbox;

	//%LE Widget_Declaration list end
};

} // namespace GUI

} // namespace RoR

