
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_RigEditorNodePanelLayout.h"

using namespace RoR;
using namespace GUI;

RigEditorNodePanelLayout::RigEditorNodePanelLayout(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

RigEditorNodePanelLayout::~RigEditorNodePanelLayout()
{
}

