
// ----------------------------------------------------------------------------
// Generated by MyGUI's LayoutEditor using RoR's code templates.
// Find the templates at [repository]/tools/MyGUI_LayoutEditor/
//
// IMPORTANT:
// Do not modify this code directly. Create a derived class instead.
// ----------------------------------------------------------------------------

#include "GUI_#{Panel_Name}.h"

using namespace RoR;
using namespace GUI;

#{Panel_Name}::#{Panel_Name}(MyGUI::Widget* _parent)
{
	initialiseByAttributes(this, _parent);
}

#{Panel_Name}::~#{Panel_Name}()
{
}
