#ifndef CAELUMCONFIG_H__
#define CAELUMCONFIG_H__

/* Define the library version */
#define CAELUM_VERSION_MAIN 0
#define CAELUM_VERSION_SEC  6
#define CAELUM_VERSION_TER  3
#define CAELUM_VERSION = (CAELUM_VERSION_MAIN << 16) | (CAELUM_VERSION_SEC << 8) | CAELUM_VERSION_TER

#define CAELUM_SCRIPT_SUPPORT 1

#define CAELUM_EXPORT

#endif //CAELUMCONFIG_H__
