set(out_dir "${CMAKE_SOURCE_DIR}/redist/lib/")

function(copy_lib name)
    set(path "/usr/lib/x86_64-linux-gnu/${name}.so")
    set(I "0")

    while(NOT EXISTS ${path} AND ${I} LESS_EQUAL "100")
        set(path "/usr/lib/x86_64-linux-gnu/${name}.so.${I}")
        MATH(EXPR I "${I}+1")
    endwhile()
    
    if(EXISTS ${path})
        file(COPY ${path} DESTINATION ${out_dir} FOLLOW_SYMLINK_CHAIN)
        message("Copy ${path}")
    else()
        message("Not found: ${path}")
    endif()
endfunction()

file(MAKE_DIRECTORY ${out_dir})

copy_lib("libzzip")
copy_lib("libfreeimage")
copy_lib("libjpeg")
copy_lib("libjpegxr")
copy_lib("libjxrglue")
copy_lib("libraw")
copy_lib("libwebp")
copy_lib("libwebpmux")
copy_lib("libIlmImf-2_3")
# copy_lib("libjasper")
copy_lib("libHalf")
copy_lib("libIex-2_3")
copy_lib("libpng16")
copy_lib("libIlmThread-2_3")
copy_lib("libCg")
copy_lib("libjpeg")
copy_lib("libXaw")