#!/bin/bash
source "$TRAVIS_BUILD_DIR"/tools/travis/linux/config

cmake \
-DCMAKE_INSTALL_PREFIX="$ROR_INSTALL_DIR" \
-DROR_USE_MYGUI="TRUE" \
-DROR_USE_OPENAL="TRUE" \
-DROR_USE_SOCKETW="TRUE" \
-DCMAKE_CXX_FLAGS="-O0" \
.

make $ROR_MAKEOPTS
