---
name: Build Windows

on: [push, pull_request]

jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Install Microsoft DirectX SDK
        shell: cmake -P {0}
        run: |
          set(BASE_DIR "C:/apps/Microsoft DirectX SDK")
          file(MAKE_DIRECTORY ${BASE_DIR})
          file(DOWNLOAD https://vps.anotherfoxguy.com/ipfs/QmZm8WtxLxpmgxmYDTMPYjsbwmipr3KtrkPgGJoYiGBqhx "$ENV{TMP}/dl.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/dl.zip" WORKING_DIRECTORY "${BASE_DIR}")

      - name: Cache conan
        uses: actions/cache@v1
        with:
          key: conan-root-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan

      - name: Cache conan packages
        uses: actions/cache@v1
        with:
          key: conan-pkg-${{ hashFiles('**/conanfile.txt') }}
          path: C:/.conan/

      - name: Install dependencies
        run: |
          choco install ninja -y

          choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
        shell: powershell

      - name: Configure
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          SET PATH=%PATH%;C:\Program Files\Conan\conan\

          SET DXSDK_DIR=C:\apps\Microsoft DirectX SDK

          cmake -GNinja -DCMAKE_BUILD_TYPE=Release .
        shell: cmd

      - name: Build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          SET PATH=%PATH%;C:\Program Files\Conan\conan\

          SET DXSDK_DIR=C:\apps\Microsoft DirectX SDK

          ninja
        shell: cmd

      - name: Clean Conan pkgs
        run: |
          "C:\Program Files\Conan\conan\conan.exe" remove * -fsb
        shell: cmd
